### PR TITLE
use qualified path for go mod

### PR DESCRIPTION
**Pull request by Ahmadkashif**
Solves #113

### CODE REVIEW

**Review by varuntechie — APPROVED** [review]

**Comment by Ahmadkashif** [comment]
@varuntechie Hi, 

I can see builds failing, I'll try to fix this if this is halting the resolution of this issue.

**Comment by NeetishPathak** [comment]
Build to be fixed. Also please make the changes in the dev branch directly and raise a PR.

**Comment by Ahmadkashif** [comment]
Hi @NeetishPathak @varuntechie , I have fixed both builds locally, should work fine here as well.

**Comment by Ahmadkashif** [comment]
Hi @NeetishPathak , @varuntechie 

What else can I do to move this PR forward?

**Comment by Ahmadkashif** [comment]
Hi @NeetishPathak , @varuntechie

I have resolved conflicts as well. What can I do to move this forward?

**Review by NeetishPathak — COMMENTED** [review]
LGTM

**Pull request merged**
